import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

// Dev-only dev server for the Electron renderer (prod build stays on bun
// build). @musepi/collab-web resolves via its package exports straight to
// TS source, so renderer edits across both packages hot-update. CSS keeps
// the existing CLI pipeline (tailwind.out.css is generated by
// `bun run tailwind` and imported from main.tsx) — Vite serves it as a
// plain file and HMRs it on regeneration.
export default defineConfig({
	plugins: [react()],
	server: {
		port: 5173,
		strictPort: true,
		host: "127.0.0.1",
	},
});
